"""initial tables

Revision ID: f2ebe576cbd1
Revises: 
Create Date: 2025-10-24 14:56:32.916210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2ebe576cbd1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_hot_events_occurred', table_name='hot_events')
    op.drop_index('idx_hot_events_user', table_name='hot_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_hot_events_user', 'hot_events', ['user_id'], unique=False)
    op.create_index('idx_hot_events_occurred', 'hot_events', ['occurred_at'], unique=False)
    # ### end Alembic commands ###
